version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: pluga_db
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - pluga_db_data:/var/lib/postgresql/data
    networks:
      - pluga_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: ${RAILS_TARGET:-development}
    container_name: pluga_backend
    env_file:
      - ./server/.env
    environment:
      - PIDFILE=/tmp/puma.pid
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pluga_network
    volumes:
      - type: bind
        source: ./server
        target: /app
        consistency: delegated

      - pluga_bundle:/usr/local/bundle
      - pluga_storage:/app/storage
      - pluga_rails_tmp:/app/tmp

    command: >
      sh -c "
        rm -f /app/tmp/pids/server.pid &&
        bundle check || bundle install &&
        bin/rails db:prepare &&
        bin/rails s -b 0.0.0.0 -p 3000
      "

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pluga_frontend
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - pluga_network
    volumes:
      - type: bind
        source: ./client
        target: /app
        consistency: cached
      - /app/node_modules
    command: >
      sh -c "
        npm run dev -- --hostname 0.0.0.0 -p 4000
      "

networks:
  pluga_network:
    driver: bridge

volumes:
  pluga_db_data:
  pluga_storage:
  pluga_bundle:
  pluga_rails_tmp:
  pluga_node_modules:
